name: snapcraft

on:
  schedule:
    - cron: '44 3 * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # main
      id: build
    - uses: snapcore/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40 # main
      env:
        SNAPCRAFT_STORE_CREDENTIALS: "foo"
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge