name: tmp

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tmp:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'pull_request'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: sudo snap install --edge --classic just-an-installer
      - run: just-an-installer --version

